apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payflow

resources:
  - namespace.yaml
  - configmaps/app-config.yaml
  # db-secrets: added by overlay (local: placeholder secret; EKS: created by External Secrets Operator)
  - deployments/api-gateway.yaml
  - deployments/auth-service.yaml
  - deployments/wallet-service.yaml
  - deployments/transaction-service.yaml
  - deployments/notification-service.yaml
  - deployments/frontend.yaml
  - db-migration-job.yaml
  - jobs/transaction-timeout-handler.yaml
  - policies/network-policies.yaml
  - policies/pod-disruption-budgets.yaml
  - policies/resource-quotas.yaml
  - autoscaling/hpa.yaml

labels:
  - pairs:
      app: payflow
      managed-by: kustomize
    includeSelectors: false
